#!/sbin/busybox sh

if [ "a$2" != "a" ];then
  gestures7=$2
fi

case "${gestures7}" in
  app1)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.browser\/.BrowserActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app2)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.calendar\/.AllInOneActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app3)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.sec.android.app.camera\/.Camera"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app4)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.contacts\/.activities.PeopleActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app5)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.email\/.activity.Welcome"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app6)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.darekxan.extweaks.app\/.ExTweaksActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app7)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.cooliris.media\/.Gallery"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app8)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.google.android.gm\/.GmailActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app9)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.google.android.apps.maps\/com.google.android.maps.MapsActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app10)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.google.android.apps.maps\/com.google.android.maps.LatitudeActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app11)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.google.android.apps.maps\/com.google.android.maps.PlacesActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app12)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.google.android.apps.maps\/com.google.android.maps.driveabout.app.DestinationActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app13)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.google.android.googlequicksearchbox\/.SearchActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app14)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.sec.android.app.controlpanel\/.activity.JobManagerActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app15)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.mms\/.ui.ConversationComposer"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app16)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.google.android.music\/com.google.android.music.activitymanagement.TopLevelActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app17)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.contacts\/.activities.DialtactsActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app18)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.vending\/.AssetBrowserActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app19)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.lidroid.quickpanel\/.MainActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app20)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.Settings"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app21)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.wifi.WifiSettings"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app22)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.bluetooth.BluetoothSettings"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app23)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.TetherSettings"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app24)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.LanguageSettings"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app25)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.UserDictionarySettings"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app26)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.SoundSettings"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app27)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.DisplaySettings"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app28)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.DockSettings"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app29)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.applications.ManageApplications"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app30)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.SecuritySettings"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app31)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.DevelopmentSettings"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app32)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.UsbSettings"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app33)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.wifi.mobileap.WifiApSettings"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app34)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.android.settings\/.fuelgauge.PowerUsageSummary"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app35)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="eu.chainfire.supersu\/.MainActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app36)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.google.android.talk\/.BuddyListCombo"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app38)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.sec.android.app.calculator\/.Calculator"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app40)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.sec.android.app.videoplayer\/.activity.MainTab"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app41)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.google.android.voicesearch\/.RecognitionActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  app42)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="com.google.android.youtube\/.HomeActivity"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;	
  recent)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="recent"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  music)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="music"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  switchapp)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="switchapp"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  bluetooth)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="bluetooth"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  data)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="data"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  wifi)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="wifi"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  wimax)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/app7=".*"/app7="wimax"/g' /data/.kuban/6gestures.sh
	sed -i 's/ges7=".*"/ges7="on"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures7=.*/gestures7=$2/g' /data/.kuban/default.profile
    ;;
  off)
	pkill -f "6gestures.sh"
	pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture"
	sed -i 's/ges7=".*"/ges7="off"/g' /data/.kuban/6gestures.sh
	/sbin/busybox sh /data/.kuban/6gestures.sh
	sed -i 's/gestures1=.*/gestures1=$2/g' /data/.kuban/default.profile
	;;
esac;

echo $gestures7