#!/sbin/busybox sh

if [ "a$2" != "a" ];then
  scaling_governor_charging=$2
fi

sed -i 's/scaling_governor_charging=.*/scaling_governor_charging=$2/g' /data/.kuban/default.profile

echo $scaling_governor_charging
