#!/sbin/busybox sh

if [ "a$2" != "a" ];then
  scaling_min_freq_sleep=$2
fi

sed -i 's/scaling_min_freq_sleep=.*/scaling_min_freq_sleep=$2/g' /data/.kuban/default.profile

echo $scaling_min_freq_sleep
