#!/sbin/busybox sh

if [ "a$2" != "a" ];then
  scaling_governor_sleep=$2
fi

sed -i 's/scaling_governor_sleep=.*/scaling_governor_sleep=$2/g' /data/.kuban/default.profile

echo $scaling_governor_sleep
